AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - my.service::my-service
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  MyServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: my.service.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: s3://niso-lambda-bucket/47012e3c1e59b6564204a0b5452051aa
      MemorySize: 1024
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 90
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
Outputs:
  MyServiceApi:
    Description: URL for application
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping
    Export:
      Name: MyServiceApi
